using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using tfl_stats.Tfl;
using TflNetworkBuilder;

namespace TestTflNetworkBuilder
{
    [Collection("HttpClientFactory collection")]
    public class StationOrderTests
    {
        public StationOrderTests()
        {
        }

        [Fact]
        public void TestTwoStationLine()
        {
            HashSet<StationNode> nodes = [];
            StationNode first = NewStation("first", nodes);
            AddStationsAfter(first, ["second"], nodes);


            var stationGraph = StationGraph.StationGraphFromTestData(nodes);

            var orderedStations = stationGraph.OrderedNodes.Select(s => s.StationId).ToList();

            Assert.Equal(orderedStations, ["START", "first", "second", "END"]);
        }

        //
        // first -> fork -> l1 -> l2 -> l3  
        //                \-> r1 -> r2
        //
        [Fact]
        public void TestForks()
        {
            HashSet<StationNode> nodes = [];
            StationNode first = NewStation("first", nodes);
            var fork = AddStationsAfter(first, ["fork"], nodes).Last();

            // line splits into two
            var left = AddStationsAfter(fork, ["l1", "l2", "l3"], nodes).Last();
            var right = AddStationsAfter(fork, ["r1", "r2"], nodes).Last();


            var stationGraph = StationGraph.StationGraphFromTestData(nodes);

            var orderedStations = stationGraph.OrderedNodes.Select(s => s.StationId).ToList();

            //
            // The line forks and the algorithm chooses to append the shorter branch first.
            //
            Assert.Equal(orderedStations, ["START", "first", "fork", "r1", "r2", "l1", "l2", "l3", "END"]);
        }

        //
        // first -> fork -> l1 -> l2 -> l3 -> ↓
        //                \-> r1 -> r2 ------>merge -> last
        //
        [Fact]
        public void TestForkThenMerge()
        {
            HashSet<StationNode> nodes = [];
            StationNode first = NewStation("first", nodes);
            var fork = AddStationsAfter(first, ["fork"], nodes).Last();

            // line splits into two
            var left = AddStationsAfter(fork, ["l1", "l2", "l3"], nodes).Last();
            var right = AddStationsAfter(fork, ["r1", "r2"], nodes).Last();

            // line rejoins at merge
            var merge = AddStationsAfter(left, ["merge"], nodes).Last();
            right.AddNext(merge);

            AddStationsAfter(merge, ["last"], nodes);

            var stationGraph = StationGraph.StationGraphFromTestData(nodes);

            var orderedStations = stationGraph.OrderedNodes.Select(s => s.StationId).ToList();

            //
            // When the line merges, the algorithm chooses to append the longer branch first.
            // This overrides whatever the earlier fork would have wanted
            //
            Assert.Equal(orderedStations, ["START", "first", "fork", "l1", "l2", "l3", "r1", "r2", "merge", "last","END"]);
        }

        //
        //  l1 -> l2 -> l3 -> ↓
        //  r1 -> r2 ------>merge -> last
        //
        [Fact]
        public void TestMerge()
        {
            HashSet<StationNode> nodes = [];

            StationNode l1 = NewStation("l1", nodes);
            var left = AddStationsAfter(l1, ["l2", "l3", "l4"], nodes).Last();

            StationNode r1 = NewStation("r1", nodes);
            var right = AddStationsAfter(r1, ["r2"], nodes).Last();

            // line rejoins at merge
            var merge = AddStationsAfter(left, ["merge"], nodes).Last();
            right.AddNext(merge);

            AddStationsAfter(merge, ["last"], nodes);

            var stationGraph = StationGraph.StationGraphFromTestData(nodes);

            var orderedStations = stationGraph.OrderedNodes.Select(s => s.StationId).ToList();

            //
            // When the line merges, the algorithm chooses to append the longer branch first.
            // This overrides whatever the earlier fork would have wanted
            //
            Assert.Equal(orderedStations, ["START", "l1", "l2", "l3", "l4", "r1", "r2", "merge", "last", "END"]);
        }

        //
        // Unit test generated by ChatGPT
        //
        [Fact]
        public void TestMatrix()
        {
            HashSet<StationNode> nodes = [];
            StationNode first = NewStation("first", nodes);
            var fork = AddStationsAfter(first, ["fork"], nodes).Last();
            // line splits into two
            var left = AddStationsAfter(fork, ["l1", "l2", "l3"], nodes).Last();
            var right = AddStationsAfter(fork, ["r1", "r2"], nodes).Last();
            // line rejoins at merge
            var merge = AddStationsAfter(left, ["merge"], nodes).Last();
            right.AddNext(merge);
            AddStationsAfter(merge, ["last"], nodes);
            // add a second fork
            var secondFork = AddStationsAfter(merge, ["second-fork"], nodes).Last();
            var secondLeft = AddStationsAfter(secondFork, ["sl1", "sl2"], nodes).Last();
            var secondRight = AddStationsAfter(secondFork, ["sr1", "sr2"], nodes).Last();
            // add a third fork
            var thirdFork = AddStationsAfter(secondLeft, ["third-fork"], nodes).Last();
            var thirdLeft = AddStationsAfter(thirdFork, ["tl1", "tl2"], nodes).Last();
            var thirdRight = AddStationsAfter(thirdFork, ["tr1", "tr2"], nodes).Last();
            // add a fourth fork
            var fourthFork = AddStationsAfter(thirdLeft, ["fourth-fork"], nodes).Last();
            var fourthLeft = AddStationsAfter(fourthFork, ["fl1", "fl2"], nodes).Last();
            var fourthRight = AddStationsAfter(fourthFork, ["fr1", "fr2"], nodes).Last();
            // add a fifth fork
            var fifthFork = AddStationsAfter(fourthLeft, ["fifth-fork"], nodes).Last();
            var fifthLeft = AddStationsAfter(fifthFork, ["fifth-l1", "fifth-l2"], nodes).Last();
            var fifthRight = AddStationsAfter(fifthFork, ["fifth-r1", "fifth-r2"], nodes).Last();
            // add a sixth fork
            var sixthFork = AddStationsAfter(fifthLeft, ["sixth-fork"], nodes).Last();
            var sixthLeft = AddStationsAfter(sixthFork, ["sixth-l1", "sixth-l2"], nodes).Last();
            var sixthRight = AddStationsAfter(sixthFork, ["sixth-r1", "sixth-r2"], nodes).Last();

            var stationGraph = StationGraph.StationGraphFromTestData(nodes);

            var orderedStations = stationGraph.OrderedNodes;

            Assert.Equal("WHO KNOWS!", "WHO KNOWS!"); // Placeholder assertion, need a piece of paper.

            // But we can check that no station is above or below its predecessors or successors
            foreach (var station in orderedStations)
            {
                foreach (var next in station.Next)
                {
                    Assert.True(next.Station.Index > station.Station.Index);
                }

                foreach (var prev in station.Prev)
                {
                    Assert.True(prev.Station.Index < station.Station.Index);
                }
            }

        }
        private static StationNode NewStation(string l, HashSet<StationNode> nodes)
        {
            var n = new StationNode { Station = new() { StationId = l } };
            nodes.Add(n);
            return n;
        }

        //
        // Adds a line of one or more stations after the given node.
        //
        private List<StationNode> AddStationsAfter(StationNode node, List<string> names, HashSet<StationNode> nodes)
        {
            List<StationNode> addedStations = [];
            var currentNode = node;
            foreach (var name in names)
            {
                var nextNode = NewStation(name, nodes);
                addedStations.Add(nextNode);
                currentNode.AddNext(nextNode);
                currentNode = nextNode;
            }
            return addedStations;
        }

    }


}
